# Generated by Django 3.1.5 on 2021-01-14 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstable',
            options={},
        ),
        migrations.RemoveField(
            model_name='productstable',
            name='created',
        ),
        migrations.AddField(
            model_name='productstable',
            name='pprice',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='carttable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuser', models.EmailField(max_length=254)),
                ('cqty', models.IntegerField()),
                ('cuserproducts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapiapp.productstable')),
            ],
        ),
    ]
